### ISSUE TITLE
React useState is not working

### ISSUE THREAD

**Issue by pinomo1** [ZetyByte/ClipSync#10]
Even though changes may be seen in useEffect, [keyPair useState](https://github.com/ZetyByte/ClipSync/blob/662e4cd52199f20338788edcfb92d70896726413/client/app/page.tsx#LL19C11-L19C11) is reset to null when called.

**Comment by Grustamli** [comment]
I am looking into it

**Comment by Grustamli** [comment]
Did you check localKeyPair is non-null ?
https://github.com/ZetyByte/ClipSync/blob/662e4cd52199f20338788edcfb92d70896726413/client/app/page.tsx#L55

**Comment by Grustamli** [comment]
BTW, Instead of promises .then, use async/await as shown in https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey#rsa_key_pair_generation

**Comment by pinomo1** [comment]
> Did you check localKeyPair is non-null ?
> 
> https://github.com/ZetyByte/ClipSync/blob/662e4cd52199f20338788edcfb92d70896726413/client/app/page.tsx#L55

console.log 1-2 lines below shows that localKeyPair is non-null, useEffect is also called on setKeyPair and it shows that variable has changed to non-null CryptoKeyPair object, but variable somehow "resets" to null. This problem is not observed in case with peerLocalKey and non-reactive variable

**Comment by Grustamli** [comment]
I didn't run the program. I'll check and try fixing it. Meanwhile, do as I suggested. Instead of Promise.then await the result.

**Comment by Grustamli** [comment]
I looked at the code. If you look at your console logs, "Generated key pair: " is not printed. Therefore, keyPair generation code on line 65 is not even called yet. 
But it seems that useEffect is called on first render anyway, hence you see null value. Try extracting line 65 into its own function and generate key pair regardless of the connection as an experiment. You should find it working then.

**Comment by Pavel418** [comment]
issue fixed by using dependences (waiting for the key pair to be assigned before establishing connection)
