### ISSUE TITLE
JSEncrypt runtime error: "window is not defined"

### ISSUE THREAD

**Issue by pinomo1** [ZetyByte/ClipSync#13]
"ReferenceError: window is not defined" when using JSEncrypt. Maybe because of SSR and Next.js, because there is no browser window on server-side, I suppose?

**Comment by alik-r** [comment]
It seems like the commit `https://github.com/ZetyByte/ClipSync/tree/aac0ed058a4c8dbac573bf4283db67036b5168a6` of #15 introduced the issue again.

**Comment by Pavel418** [comment]
@alik-r i solved the issue in #24 by just adding await keyword, however I have not encountered ReferenceError: window is not defined error.
