### ISSUE TITLE
Server overloading protection measures

### ISSUE THREAD

**Issue by Pavel418** [ZetyByte/ClipSync#17]
As we already discussed, server's power and websockets number is not unlimited, so we should work on decreasing load as much as possible. 
I suggest disconnecting clients from the server if no one has connected  to them after a certain time period (1-5 minutes) to prevent spending resources on them.
Same deadline system can be added to accepting or rejecting pairing and to idle clients who are not sending anything to the chat for a long time.

**Comment by Grustamli** [comment]
Yes, definitely there needs activity time frame. This should be configurable and should not be hardcoded. 
It should be enough to implement it in the backend. After some inactivity period, server closes the socket, thus by the nature of protocol, client is acknowledged about the interrupted connection.
